#!/bin/sh

make_files_in_commits()
{
    if [[ $# -lt 1 ]]; then
	return 0
    fi

    orig_branch=`git symbolic-ref --short HEAD`
    git stash
    git checkout -b '(make__files)'

    echo "\nHEAD is now at `git show HEAD --oneline | head -n 1`"

    num_commits=`git log --oneline --no-merges | wc -l`
    makefile_deleted=0
    while [[ $num_commits != 1 ]]
    do
	msg_of_make=`make -i 2>&1`
	if [[ ${msg_of_make#*ERROR} !=  $msg_of_make ]] ||
	       [[ ${msg_of_make#*"has not been found in loadpath"} != $msg_of_make ]]; then
	    echo "error"
	    break
	fi

	echo $msg_of_make
	commit_no=`git log --oneline --no-merges -n 1 | cut -f 1 -d ' '`
	if [[ $1 == $commit_no* ]]; then
	    break
	fi
	if [[ $commit_no == $1* ]]; then
	    break
	fi

	added_file=`git log --oneline --name-status -n 2 | grep ^A`
	if [[ ${added_file#*Makefile} != $added_file ]]; then
	    git rm --cached Makefile > /dev/null
	    git commit --amend --allow-empty -C HEAD > /dev/null
	    echo "Makefile is added at this commit."
	    echo "Makefile is untracked now."
	    makefile_deleted=1
	fi

	echo
	git reset --hard HEAD^
	num_commits=$((--num_commits))
    done

    echo
    if [ $makefile_deleted == 1 ]; then
	git add Makefile > /dev/null
	git commit -m 'Add Makefile.' > /dev/null
    fi
    git checkout $orig_branch

    git stash pop
    git branch -D '(make__files)'

    return 1
}

make_files_in_commits $1

if [[ $? == 0 ]]; then
    echo 'A commit ID is required.'
fi
